language: android
jdk: oraclejdk7
env:
matrix:
- ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
global:
- MALLOC_ARENA_MAX=2
android:
components:
- tools
- android-23
- build-tools-23.0.2
- extra-google-google_play_services
- extra-android-support
- extra-android-m2repository
- extra-google-m2repository
- sys-img-armeabi-v7a-android-21
sudo: required
script:
- ./gradlew clean build
notifications:
email: false
